/**
 * 课程数据导入导出工具
 * 统一的 JSON 处理逻辑
 */


/**
 * 下载内容为文件
 * @param {string} content - 文件内容
 * @param {string} filename - 文件名
 * @param {string} type - MIME类型
 */
function downloadFile(content, filename, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

/**
 * 导出为 CSV 格式
 * @param {Array} data - 课程数据
 * @param {string} filename - 文件名
 */
export function exportToCSV(data, filename = 'course_export') {
  const headers = ['English', 'Chinese', 'Phonetic', 'Notes'];
  const rows = data.map(item => {
    return [
      item.sentence || '',
      item.translation || item.chinese || '',
      item.phonetic_sentence || '',
      item.note || ''
    ].map(field => {
      // 处理包含逗号或引号的字段
      const stringField = String(field);
      if (stringField.includes(',') || stringField.includes('"') || stringField.includes('\n')) {
        return `"${stringField.replace(/"/g, '""')}"`;
      }
      return stringField;
    }).join(',');
  });
  
  const csvContent = '\uFEFF' + [headers.join(','), ...rows].join('\n'); // 添加 BOM 以支持中文
  downloadFile(csvContent, `${filename}.csv`, 'text/csv;charset=utf-8');
}

/**
 * 导出为 SQL 插入语句
 * @param {Array} data - 课程数据
 * @param {string} filename - 文件名
 */
export function exportToSQL(data, filename = 'course_export') {
  const tableName = 'sentences';
  const statements = data.map(item => {
    const english = (item.sentence || '').replace(/'/g, "''");
    const chinese = (item.translation || item.chinese || '').replace(/'/g, "''");
    const phonetic = (item.phonetic_sentence || '').replace(/'/g, "''");
    
    return `INSERT INTO ${tableName} (english, chinese, phonetic) VALUES ('${english}', '${chinese}', '${phonetic}');`;
  }).join('\n');
  
  const sqlContent = `-- Generated by Sentence Flow\n\n${statements}`;
  downloadFile(sqlContent, `${filename}.sql`, 'application/sql');
}

/**
 * 导出为 Anki 导入格式 (TXT, Tab分隔)
 * @param {Array} data - 课程数据
 * @param {string} filename - 文件名
 */
export function exportToAnki(data, filename = 'course_export') {
  const rows = data.map(item => {
    const front = item.sentence || '';
    const back = `${item.translation || item.chinese || ''}<br><br>${item.phonetic_sentence || ''}`;
    return `${front}\t${back}`;
  });
  
  const content = rows.join('\n');
  downloadFile(content, `${filename}_anki.txt`, 'text/plain;charset=utf-8');
}

/**
 * 下载课程数据为 JSON 文件
 * @param {Array} data - 课程数据
 * @param {string} filename - 文件名（不含扩展名）
 */
export function downloadCourseJSON(data, filename = 'course_export') {
  const jsonString = JSON.stringify(data, null, 2);
  downloadFile(jsonString, `${filename}.json`, 'application/json');
}


/**
 * 解析上传的 JSON 文件
 * @param {File} file - 上传的文件
 * @returns {Promise<Array>} 解析后的数据
 */
export function parseUploadedJSON(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const data = JSON.parse(event.target.result);
        if (!Array.isArray(data)) {
          reject(new Error('JSON 格式错误：必须是句子数组'));
          return;
        }
        resolve(data);
      } catch (err) {
        reject(new Error('JSON 解析失败：' + err.message));
      }
    };
    reader.onerror = () => reject(new Error('文件读取失败'));
    reader.readAsText(file);
  });
}

/**
 * 验证句子数据格式
 * @param {Array} data - 待验证的数据
 * @returns {{ valid: Array, errors: Array }} 有效数据和错误列表
 */
export function validateSentenceData(data) {
  const errors = [];
  const valid = data.filter((item, index) => {
    if (!item || typeof item !== 'object') {
      errors.push(`第${index + 1}项不是有效的对象`);
      return false;
    }
    if (!item.sentence || typeof item.sentence !== 'string' || item.sentence.trim() === '') {
      errors.push(`第${index + 1}项缺少 sentence 字段或为空`);
      return false;
    }
    return true;
  });
  return { valid, errors };
}

/**
 * 合并句子数据，处理 ID 冲突
 * @param {Array} existing - 现有数据
 * @param {Array} newData - 新数据
 * @returns {Array} 合并后的数据
 */
export function mergeSentenceData(existing, newData) {
  const maxId = existing.length > 0 ? Math.max(...existing.map(s => s.id || 0)) : 0;
  const existingIds = new Set(existing.map(s => s.id));

  const deduplicatedData = newData.map((item, index) => {
    if (item.id && !existingIds.has(item.id)) {
      return item;
    }
    return { ...item, id: maxId + index + 1 };
  });

  return [...existing, ...deduplicatedData];
}

/**
 * 从剪贴板读取 JSON 数据
 * @returns {Promise<Array>} 解析后的数据
 */
export async function readFromClipboard() {
  if (!navigator.clipboard) {
    throw new Error('您的浏览器不支持剪贴板访问');
  }
  const text = await navigator.clipboard.readText();
  if (!text) {
    throw new Error('剪贴板为空');
  }
  const data = JSON.parse(text);
  if (!Array.isArray(data)) {
    throw new Error('剪贴板数据必须是句子数组');
  }
  return data;
}

/**
 * JSON 格式示例
 */
export const JSON_FORMAT_EXAMPLE = [
  {
    id: 1,
    sentence: "Example sentence here.",
    translation: "例句翻译",
    phonetic_sentence: "/ɪɡˈzæmpəl ˈsentəns hɪr/",
    words: [
      { text: "Example", phonetic: "/ɪɡˈzæmpəl/", pos: "n.", meaning: "示例" }
    ]
  }
];

export function showFormatExample() {
  alert('JSON 格式示例:\n\n' + JSON.stringify(JSON_FORMAT_EXAMPLE, null, 2));
}
