/**
 * Course Enrichment Script
 * 
 * This script automatically enriches course JSON files by adding complete word definitions.
 * Run: node scripts/enrich-courses.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DICTS_DIR = path.join(__dirname, '../public/dicts');

// Complete dictionary of common English words
const COMPLETE_DICTIONARY = {
  // Articles
  "a": { phonetic: "/ə/", pos: "art.", meaning: "一(个)" },
  "an": { phonetic: "/æn/", pos: "art.", meaning: "一(个)" },
  "the": { phonetic: "/ðə/", pos: "art.", meaning: "这/那" },
  
  // Pronouns
  "i": { phonetic: "/aɪ/", pos: "pron.", meaning: "我" },
  "you": { phonetic: "/juː/", pos: "pron.", meaning: "你" },
  "he": { phonetic: "/hiː/", pos: "pron.", meaning: "他" },
  "she": { phonetic: "/ʃiː/", pos: "pron.", meaning: "她" },
  "it": { phonetic: "/ɪt/", pos: "pron.", meaning: "它" },
  "we": { phonetic: "/wiː/", pos: "pron.", meaning: "我们" },
  "they": { phonetic: "/ðeɪ/", pos: "pron.", meaning: "他们" },
  "me": { phonetic: "/miː/", pos: "pron.", meaning: "我(宾)" },
  "him": { phonetic: "/hɪm/", pos: "pron.", meaning: "他(宾)" },
  "her": { phonetic: "/hɜːr/", pos: "pron.", meaning: "她(宾)" },
  "us": { phonetic: "/ʌs/", pos: "pron.", meaning: "我们(宾)" },
  "them": { phonetic: "/ðem/", pos: "pron.", meaning: "他们(宾)" },
  "my": { phonetic: "/maɪ/", pos: "pron.", meaning: "我的" },
  "your": { phonetic: "/jɔːr/", pos: "pron.", meaning: "你的" },
  "his": { phonetic: "/hɪz/", pos: "pron.", meaning: "他的" },
  "her": { phonetic: "/hɜːr/", pos: "pron.", meaning: "她的" },
  "its": { phonetic: "/ɪts/", pos: "pron.", meaning: "它的" },
  "our": { phonetic: "/aʊər/", pos: "pron.", meaning: "我们的" },
  "their": { phonetic: "/ðeər/", pos: "pron.", meaning: "他们的" },
  "this": { phonetic: "/ðɪs/", pos: "pron.", meaning: "这" },
  "that": { phonetic: "/ðæt/", pos: "pron.", meaning: "那" },
  "these": { phonetic: "/ðiːz/", pos: "pron.", meaning: "这些" },
  "those": { phonetic: "/ðəʊz/", pos: "pron.", meaning: "那些" },
  
  // Be动词
  "am": { phonetic: "/æm/", pos: "v.", meaning: "是" },
  "is": { phonetic: "/ɪz/", pos: "v.", meaning: "是" },
  "are": { phonetic: "/ɑːr/", pos: "v.", meaning: "是" },
  "was": { phonetic: "/wɒz/", pos: "v.", meaning: "是(过去式)" },
  "were": { phonetic: "/wɜːr/", pos: "v.", meaning: "是(过去式)" },
  "be": { phonetic: "/biː/", pos: "v.", meaning: "是/存在" },
  "been": { phonetic: "/biːn/", pos: "v.", meaning: "是(过去分词)" },
  "being": { phonetic: "/ˈbiːɪŋ/", pos: "v.", meaning: "是(现在分词)" },
  
  // 情态动词
  "can": { phonetic: "/kæn/", pos: "v.", meaning: "能/会" },
  "could": { phonetic: "/kʊd/", pos: "v.", meaning: "能/可以" },
  "will": { phonetic: "/wɪl/", pos: "v.", meaning: "将/会" },
  "would": { phonetic: "/wʊd/", pos: "v.", meaning: "会/将" },
  "shall": { phonetic: "/ʃæl/", pos: "v.", meaning: "将/应该" },
  "should": { phonetic: "/ʃʊd/", pos: "v.", meaning: "应该" },
  "may": { phonetic: "/meɪ/", pos: "v.", meaning: "可以/可能" },
  "might": { phonetic: "/maɪt/", pos: "v.", meaning: "可能" },
  "must": { phonetic: "/mʌst/", pos: "v.", meaning: "必须" },
  
  // Have动词
  "have": { phonetic: "/hæv/", pos: "v.", meaning: "有" },
  "has": { phonetic: "/hæz/", pos: "v.", meaning: "有" },
  "had": { phonetic: "/hæd/", pos: "v.", meaning: "有(过去式)" },
  "having": { phonetic: "/ˈhævɪŋ/", pos: "v.", meaning: "有(现在分词)" },
  
  // Do动词
  "do": { phonetic: "/duː/", pos: "v.", meaning: "做" },
  "does": { phonetic: "/dʌz/", pos: "v.", meaning: "做" },
  "did": { phonetic: "/dɪd/", pos: "v.", meaning: "做(过去式)" },
  "doing": { phonetic: "/ˈduːɪŋ/", pos: "v.", meaning: "做(现在分词)" },
  
  // 副词
  "not": { phonetic: "/nɒt/", pos: "adv.", meaning: "不" },
  "no": { phonetic: "/nəʊ/", pos: "adv.", meaning: "不/没有" },
  "yes": { phonetic: "/jes/", pos: "adv.", meaning: "是" },
  "very": { phonetic: "/ˈveri/", pos: "adv.", meaning: "非常" },
  "too": { phonetic: "/tuː/", pos: "adv.", meaning: "也/太" },
  "also": { phonetic: "/ˈɔːlsəʊ/", pos: "adv.", meaning: "也" },
  "only": { phonetic: "/ˈəʊnli/", pos: "adv.", meaning: "仅仅" },
  "just": { phonetic: "/dʒʌst/", pos: "adv.", meaning: "只是/刚刚" },
  "even": { phonetic: "/ˈiːvn/", pos: "adv.", meaning: "甚至" },
  "still": { phonetic: "/stɪl/", pos: "adv.", meaning: "仍然" },
  "already": { phonetic: "/ɔːlˈredi/", pos: "adv.", meaning: "已经" },
  "yet": { phonetic: "/jet/", pos: "adv.", meaning: "还/仍然" },
  "ever": { phonetic: "/ˈevər/", pos: "adv.", meaning: "曾经" },
  "never": { phonetic: "/ˈnevər/", pos: "adv.", meaning: "从不" },
  "always": { phonetic: "/ˈɔːlweɪz/", pos: "adv.", meaning: "总是" },
  "often": { phonetic: "/ˈɒfn/", pos: "adv.", meaning: "经常" },
  "usually": { phonetic: "/ˈjuːʒuəli/", pos: "adv.", meaning: "通常" },
  "sometimes": { phonetic: "/ˈsʌmtaɪmz/", pos: "adv.", meaning: "有时" },
  "again": { phonetic: "/əˈɡen/", pos: "adv.", meaning: "再次" },
  "once": { phonetic: "/wʌns/", pos: "adv.", meaning: "一次" },
  "twice": { phonetic: "/twaɪs/", pos: "adv.", meaning: "两次" },
  "here": { phonetic: "/hɪər/", pos: "adv.", meaning: "这里" },
  "there": { phonetic: "/ðeər/", pos: "adv.", meaning: "那里" },
  "now": { phonetic: "/naʊ/", pos: "adv.", meaning: "现在" },
  "then": { phonetic: "/ðen/", pos: "adv.", meaning: "那时" },
  "today": { phonetic: "/təˈdeɪ/", pos: "adv.", meaning: "今天" },
  "tomorrow": { phonetic: "/təˈmɒrəʊ/", pos: "adv.", meaning: "明天" },
  "yesterday": { phonetic: "/ˈjestərdeɪ/", pos: "adv.", meaning: "昨天" },
  "soon": { phonetic: "/suːn/", pos: "adv.", meaning: "很快" },
  "late": { phonetic: "/leɪt/", pos: "adv.", meaning: "晚/迟" },
  "early": { phonetic: "/ˈɜːrli/", pos: "adv.", meaning: "早" },
  "much": { phonetic: "/mʌtʃ/", pos: "adv.", meaning: "很多" },
  "more": { phonetic: "/mɔːr/", pos: "adv.", meaning: "更多" },
  "most": { phonetic: "/məʊst/", pos: "adv.", meaning: "最" },
  "so": { phonetic: "/səʊ/", pos: "adv.", meaning: "所以/如此" },
  "as": { phonetic: "/æz/", pos: "adv.", meaning: "像/因为" },
  "how": { phonetic: "/haʊ/", pos: "adv.", meaning: "怎样" },
  "what": { phonetic: "/wɒt/", pos: "adv.", meaning: "什么" },
  "when": { phonetic: "/wen/", pos: "adv.", meaning: "什么时候" },
  "where": { phonetic: "/weər/", pos: "adv.", meaning: "哪里" },
  "why": { phonetic: "/waɪ/", pos: "adv.", meaning: "为什么" },
  
  // 连词
  "and": { phonetic: "/ænd/", pos: "conj.", meaning: "和" },
  "but": { phonetic: "/bʌt/", pos: "conj.", meaning: "但是" },
  "or": { phonetic: "/ɔːr/", pos: "conj.", meaning: "或者" },
  "if": { phonetic: "/ɪf/", pos: "conj.", meaning: "如果" },
  "because": { phonetic: "/bɪˈkɒz/", pos: "conj.", meaning: "因为" },
  "although": { phonetic: "/ɔːlˈðəʊ/", pos: "conj.", meaning: "虽然" },
  "though": { phonetic: "/ðəʊ/", pos: "conj.", meaning: "虽然" },
  "while": { phonetic: "/waɪl/", pos: "conj.", meaning: "当...时" },
  "when": { phonetic: "/wen/", pos: "conj.", meaning: "当...时" },
  "before": { phonetic: "/bɪˈfɔːr/", pos: "conj.", meaning: "在...之前" },
  "after": { phonetic: "/ˈɑːftər/", pos: "conj.", meaning: "在...之后" },
  "until": { phonetic: "/ənˈtɪl/", pos: "conj.", meaning: "直到" },
  "since": { phonetic: "/sɪns/", pos: "conj.", meaning: "自从" },
  "unless": { phonetic: "/ənˈles/", pos: "conj.", meaning: "除非" },
  "whether": { phonetic: "/ˈweðər/", pos: "conj.", meaning: "是否" },
  
  // 介词
  "in": { phonetic: "/ɪn/", pos: "prep.", meaning: "在...里" },
  "on": { phonetic: "/ɒn/", pos: "prep.", meaning: "在...上" },
  "at": { phonetic: "/æt/", pos: "prep.", meaning: "在" },
  "to": { phonetic: "/tuː/", pos: "prep.", meaning: "到/对" },
  "from": { phonetic: "/frɒm/", pos: "prep.", meaning: "从" },
  "by": { phonetic: "/baɪ/", pos: "prep.", meaning: "通过/由" },
  "with": { phonetic: "/wɪð/", pos: "prep.", meaning: "和/带有" },
  "for": { phonetic: "/fɔːr/", pos: "prep.", meaning: "为了" },
  "of": { phonetic: "/ɒv/", pos: "prep.", meaning: "...的" },
  "about": { phonetic: "/əˈbaʊt/", pos: "prep.", meaning: "关于" },
  "into": { phonetic: "/ˈɪntuː/", pos: "prep.", meaning: "进入" },
  "over": { phonetic: "/ˈəʊvər/", pos: "prep.", meaning: "在...之上" },
  "under": { phonetic: "/ˈʌndər/", pos: "prep.", meaning: "在...下面" },
  "between": { phonetic: "/bɪˈtwiːn/", pos: "prep.", meaning: "之间" },
  "among": { phonetic: "/əˈmʌŋ/", pos: "prep.", meaning: "在...之中" },
  "through": { phonetic: "/θruː/", pos: "prep.", meaning: "通过" },
  "during": { phonetic: "/ˈdjʊərɪŋ/", pos: "prep.", meaning: "在...期间" },
  "without": { phonetic: "/wɪˈðaʊt/", pos: "prep.", meaning: "没有" },
  "within": { phonetic: "/wɪˈðɪn/", pos: "prep.", meaning: "在...之内" },
  "against": { phonetic: "/əˈɡenst/", pos: "prep.", meaning: "反对/靠着" },
  "around": { phonetic: "/əˈraʊnd/", pos: "prep.", meaning: "围绕" },
  "behind": { phonetic: "/bɪˈhaɪnd/", pos: "prep.", meaning: "在...后面" },
  "beside": { phonetic: "/bɪˈsaɪd/", pos: "prep.", meaning: "在...旁边" },
  "except": { phonetic: "/ɪkˈsept/", pos: "prep.", meaning: "除了" },
  
  // 形容词
  "good": { phonetic: "/ɡʊd/", pos: "adj.", meaning: "好的" },
  "bad": { phonetic: "/bæd/", pos: "adj.", meaning: "坏的" },
  "big": { phonetic: "/bɪɡ/", pos: "adj.", meaning: "大的" },
  "small": { phonetic: "/smɔːl/", pos: "adj.", meaning: "小的" },
  "new": { phonetic: "/njuː/", pos: "adj.", meaning: "新的" },
  "old": { phonetic: "/əʊld/", pos: "adj.", meaning: "旧的/老的" },
  "young": { phonetic: "/jʌŋ/", pos: "adj.", meaning: "年轻的" },
  "great": { phonetic: "/ɡreɪt/", pos: "adj.", meaning: "伟大的/太好了" },
  "long": { phonetic: "/lɒŋ/", pos: "adj.", meaning: "长的" },
  "short": { phonetic: "/ʃɔːt/", pos: "adj.", meaning: "短的/矮的" },
  "high": { phonetic: "/haɪ/", pos: "adj.", meaning: "高的" },
  "low": { phonetic: "/ləʊ/", pos: "adj.", meaning: "低的" },
  "right": { phonetic: "/raɪt/", pos: "adj.", meaning: "正确的/右边" },
  "wrong": { phonetic: "/rɒŋ/", pos: "adj.", meaning: "错误的" },
  "easy": { phonetic: "/ˈiːzi/", pos: "adj.", meaning: "容易的" },
  "hard": { phonetic: "/hɑːd/", pos: "adj.", meaning: "难的/硬的" },
  "fast": { phonetic: "/fɑːst/", pos: "adj.", meaning: "快的" },
  "slow": { phonetic: "/sləʊ/", pos: "adj.", meaning: "慢的" },
  "hot": { phonetic: "/hɒt/", pos: "adj.", meaning: "热的" },
  "cold": { phonetic: "/kəʊld/", pos: "adj.", meaning: "冷的" },
  "warm": { phonetic: "/wɔːm/", pos: "adj.", meaning: "温暖的" },
  "cool": { phonetic: "/kuːl/", pos: "adj.", meaning: "凉爽的" },
  "happy": { phonetic: "/ˈhæpi/", pos: "adj.", meaning: "快乐的" },
  "sad": { phonetic: "/sæd/", pos: "adj.", meaning: "悲伤的" },
  "beautiful": { phonetic: "/ˈbjuːtɪfl/", pos: "adj.", meaning: "美丽的" },
  "ugly": { phonetic: "/ˈʌɡli/", pos: "adj.", meaning: "丑陋的" },
  "rich": { phonetic: "/rɪtʃ/", pos: "adj.", meaning: "富有的" },
  "poor": { phonetic: "/pɔːr/", pos: "adj.", meaning: "贫穷的" },
  "strong": { phonetic: "/strɒŋ/", pos: "adj.", meaning: "强壮的" },
  "weak": { phonetic: "/wiːk/", pos: "adj.", meaning: "虚弱的" },
  "full": { phonetic: "/fʊl/", pos: "adj.", meaning: "满的" },
  "empty": { phonetic: "/ˈempti/", pos: "adj.", meaning: "空的" },
  "open": { phonetic: "/ˈəʊpən/", pos: "adj.", meaning: "开的" },
  "closed": { phonetic: "/kləʊzd/", pos: "adj.", meaning: "关闭的" },
  "clean": { phonetic: "/kliːn/", pos: "adj.", meaning: "干净的" },
  "dirty": { phonetic: "/ˈdɜːrti/", pos: "adj.", meaning: "脏的" },
  "dark": { phonetic: "/dɑːrk/", pos: "adj.", meaning: "黑暗的" },
  "light": { phonetic: "/laɪt/", pos: "adj.", meaning: "轻的/明亮的" },
  "heavy": { phonetic: "/ˈhevi/", pos: "adj.", meaning: "重的" },
  "soft": { phonetic: "/sɒft/", pos: "adj.", meaning: "柔软的" },
  "hard": { phonetic: "/hɑːrd/", pos: "adj.", meaning: "硬的" },
  "wet": { phonetic: "/wet/", pos: "adj.", meaning: "湿的" },
  "dry": { phonetic: "/draɪ/", pos: "adj.", meaning: "干的" },
  "fine": { phonetic: "/faɪn/", pos: "adj.", meaning: "好的/晴朗的" },
  "nice": { phonetic: "/naɪs/", pos: "adj.", meaning: "美好的" },
  "well": { phonetic: "/wel/", pos: "adj.", meaning: "健康的" },
  "ill": { phonetic: "/ɪl/", pos: "adj.", meaning: "生病的" },
  "alive": { phonetic: "/əˈlaɪv/", pos: "adj.", meaning: "活着的" },
  "dead": { phonetic: "/ded/", pos: "adj.", meaning: "死的" },
  "free": { phonetic: "/friː/", pos: "adj.", meaning: "自由的/免费的" },
  "busy": { phonetic: "/ˈbɪzi/", pos: "adj.", meaning: "忙碌的" },
  "free": { phonetic: "/friː/", pos: "adj.", meaning: "空闲的" },
  "every": { phonetic: "/ˈevri/", pos: "adj.", meaning: "每个的" },
  "each": { phonetic: "/iːtʃ/", pos: "adj.", meaning: "每个" },
  "some": { phonetic: "/sʌm/", pos: "adj.", meaning: "一些" },
  "any": { phonetic: "/ˈeni/", pos: "adj.", meaning: "任何" },
  "many": { phonetic: "/ˈmeni/", pos: "adj.", meaning: "许多" },
  "few": { phonetic: "/fjuː/", pos: "adj.", meaning: "少的" },
  "several": { phonetic: "/ˈsevrəl/", pos: "adj.", meaning: "几个" },
  "other": { phonetic: "/ˈʌðər/", pos: "adj.", meaning: "其他的" },
  "all": { phonetic: "/ɔːl/", pos: "adj.", meaning: "所有的" },
  "both": { phonetic: "/bəʊθ/", pos: "adj.", meaning: "两者" },
  "either": { phonetic: "/ˈaɪðər/", pos: "adj.", meaning: "任一的" },
  "neither": { phonetic: "/ˈnaɪðər/", pos: "adj.", meaning: "两者都不" },
  "such": { phonetic: "/sʌtʃ/", pos: "adj.", meaning: "这样的" },
  "same": { phonetic: "/seɪm/", pos: "adj.", meaning: "相同的" },
  "different": { phonetic: "/ˈdɪfrənt/", pos: "adj.", meaning: "不同的" },
  "possible": { phonetic: "/ˈpɒsəbl/", pos: "adj.", meaning: "可能的" },
  "impossible": { phonetic: "/ɪmˈpɒsəbl/", pos: "adj.", meaning: "不可能的" },
  "necessary": { phonetic: "/ˈnesəseri/", pos: "adj.", meaning: "必要的" },
  "important": { phonetic: "/ɪmˈpɔːrtənt/", pos: "adj.", meaning: "重要的" },
  "difficult": { phonetic: "/ˈdɪfɪkəlt/", pos: "adj.", meaning: "困难的" },
  "simple": { phonetic: "/ˈsɪmpl/", pos: "adj.", meaning: "简单的" },
  "special": { phonetic: "/ˈspeʃl/", pos: "adj.", meaning: "特殊的" },
  "general": { phonetic: "/ˈdʒenrəl/", pos: "adj.", meaning: "一般的" },
  "public": { phonetic: "/ˈpʌblɪk/", pos: "adj.", meaning: "公共的" },
  "private": { phonetic: "/ˈpraɪvət/", pos: "adj.", meaning: "私人的" },
  "whole": { phonetic: "/həʊl/", pos: "adj.", meaning: "整个的" },
  "last": { phonetic: "/lɑːst/", pos: "adj.", meaning: "最后的" },
  "next": { phonetic: "/nekst/", pos: "adj.", meaning: "下一个" },
  "first": { phonetic: "/fɜːrst/", pos: "adj.", meaning: "第一的" },
  "late": { phonetic: "/leɪt/", pos: "adj.", meaning: "晚的" },
  "early": { phonetic: "/ˈɜːrli/", pos: "adj.", meaning: "早的" },
  "late": { phonetic: "/leɪt/", pos: "adj.", meaning: "迟到的" },
  "present": { phonetic: "/ˈpreznt/", pos: "adj.", meaning: "在场的/现在的" },
  "absent": { phonetic: "/ˈæbsənt/", pos: "adj.", meaning: "缺席的" },
  "ready": { phonetic: "/ˈredi/", pos: "adj.", meaning: "准备好的" },
  "sure": { phonetic: "/ʃʊr/", pos: "adj.", meaning: "确定的" },
  "certain": { phonetic: "/ˈsɜːrtn/", pos: "adj.", meaning: "确定的" },
  "clear": { phonetic: "/klɪər/", pos: "adj.", meaning: "清楚的" },
  "exact": { phonetic: "/ɪɡˈzækt/", pos: "adj.", meaning: "精确的" },
  "real": { phonetic: "/riːl/", pos: "adj.", meaning: "真实的" },
  "true": { phonetic: "/truː/", pos: "adj.", meaning: "真的" },
  "false": { phonetic: "/fɔːls/", pos: "adj.", meaning: "假的" },
  "fair": { phonetic: "/feər/", pos: "adj.", meaning: "公平的" },
  "just": { phonetic: "/dʒʌst/", pos: "adj.", meaning: "公正的" },
  "due": { phonetic: "/duː/", pos: "adj.", meaning: "应付的" },
  "near": { phonetic: "/nɪər/", pos: "adj.", meaning: "近的" },
  "far": { phonetic: "/fɑːr/", pos: "adj.", meaning: "远的" },
  "own": { phonetic: "/əʊn/", pos: "adj.", meaning: "自己的" },
  "single": { phonetic: "/ˈsɪŋɡl/", pos: "adj.", meaning: "单个的" },
  "double": { phonetic: "/ˈdʌbl/", pos: "adj.", meaning: "双倍的" },
  "left": { phonetic: "/left/", pos: "adj.", meaning: "左边的" },
  "personal": { phonetic: "/ˈpɜːrsənl/", pos: "adj.", meaning: "个人的" },
  "human": { phonetic: "/ˈhjuːmən/", pos: "adj.", meaning: "人类的" },
  "national": { phonetic: "/ˈnæʃnəl/", pos: "adj.", meaning: "国家的" },
  "international": { phonetic: "/ˌɪnternæʃnəl/", pos: "adj.", meaning: "国际的" },
  "social": { phonetic: "/ˈsəʊʃl/", pos: "adj.", meaning: "社会的" },
  "political": { phonetic: "/pəˈlɪtɪkl/", pos: "adj.", meaning: "政治的" },
  "economic": { phonetic: "/ˌekəˈnɒmɪk/", pos: "adj.", meaning: "经济的" },
  "cultural": { phonetic: "/ˈkʌltʃərəl/", pos: "adj.", meaning: "文化的" },
  "religious": { phonetic: "/rɪˈlɪdʒəs/", pos: "adj.", meaning: "宗教的" },
  "scientific": { phonetic: "/ˌsaɪənˈtɪfɪk/", pos: "adj.", meaning: "科学的" },
  "modern": { phonetic: "/ˈmɒdn/", pos: "adj.", meaning: "现代的" },
  "traditional": { phonetic: "/trəˈdɪʃənl/", pos: "adj.", meaning: "传统的" },
  "common": { phonetic: "/ˈkɒmən/", pos: "adj.", meaning: "共同的" },
  "public": { phonetic: "/ˈpʌblɪk/", pos: "adj.", meaning: "公共的" },
  "private": { phonetic: "/ˈpraɪvət/", pos: "adj.", meaning: "私人的" },
  "medical": { phonetic: "/ˈmedɪkl/", pos: "adj.", meaning: "医学的" },
  "military": { phonetic: "/ˈmɪləteri/", pos: "adj.", meaning: "军事的" },
  "financial": { phonetic: "/faɪˈnænʃl/", pos: "adj.", meaning: "金融的" },
  "legal": { phonetic: "/ˈliːɡl/", pos: "adj.", meaning: "法律的" },
  "education": { phonetic: "/ˌedʒuˈkeɪʃn/", pos: "n.", meaning: "教育" },
  "development": { phonetic: "/dɪˈveləpmənt/", pos: "n.", meaning: "发展" },
  "research": { phonetic: "/ˈriːsɜːrtʃ/", pos: "n.", meaning: "研究" },
  "country": { phonetic: "/ˈkʌntri/", pos: "n.", meaning: "国家" },
  "city": { phonetic: "/ˈsɪti/", pos: "n.", meaning: "城市" },
  "world": { phonetic: "/wɜːrld/", pos: "n.", meaning: "世界" },
  "life": { phonetic: "/laɪf/", pos: "n.", meaning: "生活/生命" },
  "people": { phonetic: "/ˈpiːpl/", pos: "n.", meaning: "人们" },
  "man": { phonetic: "/mæn/", pos: "n.", meaning: "男人" },
  "woman": { phonetic: "/ˈwʊmən/", pos: "n.", meaning: "女人" },
  "child": { phonetic: "/tʃaɪld/", pos: "n.", meaning: "孩子" },
  "family": { phonetic: "/ˈfæməli/", pos: "n.", meaning: "家庭" },
  "house": { phonetic: "/haʊs/", pos: "n.", meaning: "房子" },
  "home": { phonetic: "/həʊm/", pos: "n.", meaning: "家" },
  "money": { phonetic: "/ˈmʌni/", pos: "n.", meaning: "钱" },
  "time": { phonetic: "/taɪm/", pos: "n.", meaning: "时间" },
  "year": { phonetic: "/jɪər/", pos: "n.", meaning: "年" },
  "day": { phonetic: "/deɪ/", pos: "n.", meaning: "天" },
  "week": { phonetic: "/wiːk/", pos: "n.", meaning: "周" },
  "month": { phonetic: "/mʌnθ/", pos: "n.", meaning: "月" },
  "hour": { phonetic: "/ˈaʊər/", pos: "n.", meaning: "小时" },
  "minute": { phonetic: "/ˈmɪnɪt/", pos: "n.", meaning: "分钟" },
  "second": { phonetic: "/ˈsekənd/", pos: "n.", meaning: "秒" },
  "water": { phonetic: "/ˈwɔːtər/", pos: "n.", meaning: "水" },
  "food": { phonetic: "/fuːd/", pos: "n.", meaning: "食物" },
  "book": { phonetic: "/bʊk/", pos: "n.", meaning: "书" },
  "word": { phonetic: "/wɜːrd/", pos: "n.", meaning: "单词" },
  "question": { phonetic: "/ˈkwestʃən/", pos: "n.", meaning: "问题" },
  "answer": { phonetic: "/ˈænsər/", pos: "n.", meaning: "答案" },
  "problem": { phonetic: "/ˈprɒbləm/", pos: "n.", meaning: "问题" },
  "fact": { phonetic: "/fækt/", pos: "n.", meaning: "事实" },
  "thing": { phonetic: "/θɪŋ/", pos: "n.", meaning: "事情" },
  "work": { phonetic: "/wɜːrk/", pos: "n.", meaning: "工作" },
  "job": { phonetic: "/dʒɒb/", pos: "n.", meaning: "工作/职业" },
  "school": { phonetic: "/skuːl/", pos: "n.", meaning: "学校" },
  "company": { phonetic: "/ˈkʌmpəni/", pos: "n.", meaning: "公司" },
  "government": { phonetic: "/ˈɡʌvərnmənt/", pos: "n.", meaning: "政府" },
  "group": { phonetic: "/ɡruːp/", pos: "n.", meaning: "组/群" },
  "part": { phonetic: "/pɑːrt/", pos: "n.", meaning: "部分" },
  "place": { phonetic: "/pleɪs/", pos: "n.", meaning: "地方" },
  "case": { phonetic: "/keɪs/", pos: "n.", meaning: "情况/案例" },
  "week": { phonetic: "/wiːk/", pos: "n.", meaning: "周" },
  "month": { phonetic: "/mʌnθ/", pos: "n.", meaning: "月" },
  "today": { phonetic: "/təˈdeɪ/", pos: "n.", meaning: "今天" },
  "night": { phonetic: "/naɪt/", pos: "n.", meaning: "夜晚" },
  "morning": { phonetic: "/ˈmɔːrnɪŋ/", pos: "n.", meaning: "早晨" },
  "evening": { phonetic: "/ˈiːvnɪŋ/", pos: "n.", meaning: "傍晚" },
  "road": { phonetic: "/rəʊd/", pos: "n.", meaning: "路" },
  "street": { phonetic: "/striːt/", pos: "n.", meaning: "街道" },
  "way": { phonetic: "/weɪ/", pos: "n.", meaning: "方式/路" },
  "center": { phonetic: "/ˈsentər/", pos: "n.", meaning: "中心" },
  "side": { phonetic: "/saɪd/", pos: "n.", meaning: "边/侧面" },
  "kind": { phonetic: "/kaɪnd/", pos: "n.", meaning: "种类" },
  "sort": { phonetic: "/sɔːrt/", pos: "n.", meaning: "种类" },
  "type": { phonetic: "/taɪp/", pos: "n.", meaning: "类型" },
  "form": { phonetic: "/fɔːrm/", pos: "n.", meaning: "形式" },
  "system": { phonetic: "/ˈsɪstəm/", pos: "n.", meaning: "系统" },
  "program": { phonetic: "/ˈprəʊɡræm/", pos: "n.", meaning: "程序/项目" },
  "project": { phonetic: "/ˈprɒdʒekt/", pos: "n.", meaning: "项目" },
  "information": { phonetic: "/ˌɪnfərˈmeɪʃn/", pos: "n.", meaning: "信息" },
  "news": { phonetic: "/njuːz/", pos: "n.", meaning: "新闻" },
  "history": { phonetic: "/ˈhɪstri/", pos: "n.", meaning: "历史" },
  "future": { phonetic: "/ˈfjuːtʃər/", pos: "n.", meaning: "未来" },
  "past": { phonetic: "/pæst/", pos: "n.", meaning: "过去" },
  "power": { phonetic: "/ˈpaʊər/", pos: "n.", meaning: "力量/权力" },
  "control": { phonetic: "/kənˈtrəʊl/", pos: "n.", meaning: "控制" },
  "order": { phonetic: "/ˈɔːrdər/", pos: "n.", meaning: "顺序/命令" },
  "reason": { phonetic: "/ˈriːzn/", pos: "n.", meaning: "理由" },
  "idea": { phonetic: "/aɪˈdɪə/", pos: "n.", meaning: "主意" },
  "thought": { phonetic: "/θɔːt/", pos: "n.", meaning: "想法" },
  "mind": { phonetic: "/maɪnd/", pos: "n.", meaning: "头脑" },
  "heart": { phonetic: "/hɑːrt/", pos: "n.", meaning: "心" },
  "body": { phonetic: "/ˈbɒdi/", pos: "n.", meaning: "身体" },
  "face": { phonetic: "/feɪs/", pos: "n.", meaning: "脸" },
  "eye": { phonetic: "/aɪ/", pos: "n.", meaning: "眼睛" },
  "hand": { phonetic: "/hænd/", pos: "n.", meaning: "手" },
  "head": { phonetic: "/hed/", pos: "n.", meaning: "头" },
  "foot": { phonetic: "/fʊt/", pos: "n.", meaning: "脚" },
  "friend": { phonetic: "/frend/", pos: "n.", meaning: "朋友" },
  "father": { phonetic: "/ˈfɑːðər/", pos: "n.", meaning: "父亲" },
  "mother": { phonetic: "/ˈmʌðər/", pos: "n.", meaning: "母亲" },
  "parent": { phonetic: "/ˈpeərənt/", pos: "n.", meaning: "父母" },
  "brother": { phonetic: "/ˈbrʌðər/", pos: "n.", meaning: "兄弟" },
  "sister": { phonetic: "/ˈsɪstər/", pos: "n.", meaning: "姐妹" },
  "son": { phonetic: "/sʌn/", pos: "n.", meaning: "儿子" },
  "daughter": { phonetic: "/ˈdɔːtər/", pos: "n.", meaning: "女儿" },
  "wife": { phonetic: "/waɪf/", pos: "n.", meaning: "妻子" },
  "husband": { phonetic: "/ˈhʌzbənd/", pos: "n.", meaning: "丈夫" },
  
  // 常用动词
  "get": { phonetic: "/ɡet/", pos: "v.", meaning: "得到/到达" },
  "got": { phonetic: "/ɡɒt/", pos: "v.", meaning: "得到(过去式)" },
  "make": { phonetic: "/meɪk/", v: "v.", meaning: "制作" },
  "made": { phonetic: "/meɪd/", pos: "v.", meaning: "制作(过去式)" },
  "go": { phonetic: "/ɡəʊ/", pos: "v.", meaning: "去" },
  "went": { phonetic: "/went/", pos: "v.", meaning: "去(过去式)" },
  "come": { phonetic: "/kʌm/", pos: "v.", meaning: "来" },
  "came": { phonetic: "/keɪm/", pos: "v.", meaning: "来(过去式)" },
  "see": { phonetic: "/siː/", pos: "v.", meaning: "看" },
  "saw": { phonetic: "/sɔː/", pos: "v.", meaning: "看(过去式)" },
  "know": { phonetic: "/nəʊ/", pos: "v.", meaning: "知道" },
  "knew": { phonetic: "/njuː/", pos: "v.", meaning: "知道(过去式)" },
  "think": { phonetic: "/θɪŋk/", pos: "v.", meaning: "想/认为" },
  "thought": { phonetic: "/θɔːt/", pos: "v.", meaning: "想(过去式)" },
  "say": { phonetic: "/seɪ/", pos: "v.", meaning: "说" },
  "said": { phonetic: "/sed/", pos: "v.", meaning: "说(过去式)" },
  "tell": { phonetic: "/tel/", pos: "v.", meaning: "告诉" },
  "told": { phonetic: "/təʊld/", pos: "v.", meaning: "告诉(过去式)" },
  "try": { phonetic: "/traɪ/", pos: "v.", meaning: "尝试" },
  "call": { phonetic: "/kɔːl/", pos: "v.", meaning: "打电话/呼叫" },
  "keep": { phonetic: "/kiːp/", pos: "v.", meaning: "保持" },
  "kept": { phonetic: "/kept/", pos: "v.", meaning: "保持(过去式)" },
  "need": { phonetic: "/niːd/", pos: "v.", meaning: "需要" },
  "feel": { phonetic: "/fiːl/", pos: "v.", meaning: "感觉" },
  "felt": { phonetic: "/felt/", pos: "v.", meaning: "感觉(过去式)" },
  "become": { phonetic: "/bɪˈkʌm/", pos: "v.", meaning: "变成" },
  "became": { phonetic: "/bɪˈkeɪm/", pos: "v.", meaning: "变成(过去式)" },
  "leave": { phonetic: "/liːv/", pos: "v.", meaning: "离开" },
  "left": { phonetic: "/left/", pos: "v.", meaning: "离开(过去式)" },
  "put": { phonetic: "/pʊt/", pos: "v.", meaning: "放" },
  "begin": { phonetic: "/bɪˈɡɪn/", pos: "v.", meaning: "开始" },
  "began": { phonetic: "/bɪˈɡæn/", pos: "v.", meaning: "开始(过去式)" },
  "seem": { phonetic: "/siːm/", pos: "v.", meaning: "似乎" },
  "help": { phonetic: "/help/", pos: "v.", meaning: "帮助" },
  "show": { phonetic: "/ʃəʊ/", pos: "v.", meaning: "显示/展示" },
  "showed": { phonetic: "/ʃəʊd/", pos: "v.", meaning: "显示(过去式)" },
  "hear": { phonetic: "/hɪər/", pos: "v.", meaning: "听" },
  "heard": { phonetic: "/hɜːd/", pos: "v.", meaning: "听(过去式)" },
  "play": { phonetic: "/pleɪ/", pos: "v.", meaning: "玩/播放" },
  "run": { phonetic: "/rʌn/", pos: "v.", meaning: "跑" },
  "move": { phonetic: "/muːv/", pos: "v.", meaning: "移动" },
  "live": { phonetic: "/lɪv/", pos: "v.", meaning: "生活/居住" },
  "believe": { phonetic: "/bɪˈliːv/", pos: "v.", meaning: "相信" },
  "happen": { phonetic: "/ˈhæpən/", pos: "v.", meaning: "发生" },
  "write": { phonetic: "/raɪt/", pos: "v.", meaning: "写" },
  "wrote": { phonetic: "/rəʊt/", pos: "v.", meaning: "写(过去式)" },
  "provide": { phonetic: "/prəˈvaɪd/", pos: "v.", meaning: "提供" },
  "sit": { phonetic: "/sɪt/", pos: "v.", meaning: "坐" },
  "stand": { phonetic: "/stænd/", pos: "v.", meaning: "站" },
  "lose": { phonetic: "/luːz/", pos: "v.", meaning: "失去" },
  "lost": { phonetic: "/lɒst/", pos: "v.", meaning: "失去(过去式)" },
  "pay": { phonetic: "/peɪ/", pos: "v.", meaning: "支付" },
  "paid": { phonetic: "/peɪd/", pos: "v.", meaning: "支付(过去式)" },
  "meet": { phonetic: "/miːt/", pos: "v.", meaning: "遇见" },
  "met": { phonetic: "/met/", pos: "v.", meaning: "遇见(过去式)" },
  "include": { phonetic: "/ɪnˈkluːd/", pos: "v.", meaning: "包括" },
  "continue": { phonetic: "/kənˈtɪnjuː/", pos: "v.", meaning: "继续" },
  "set": { phonetic: "/set/", pos: "v.", meaning: "设置" },
  "learn": { phonetic: "/lɜːrn/", pos: "v.", meaning: "学习" },
  "learned": { phonetic: "/lɜrnd/", pos: "v.", meaning: "学习(过去式)" },
  "change": { phonetic: "/tʃeɪndʒ/", pos: "v.", meaning: "改变" },
  "lead": { phonetic: "/liːd/", pos: "v.", meaning: "领导" },
  "led": { phonetic: "/led/", pos: "v.", meaning: "领导(过去式)" },
  "understand": { phonetic: "/ˌʌndərˈstænd/", pos: "v.", meaning: "理解" },
  "watch": { phonetic: "/wɒtʃ/", pos: "v.", meaning: "观看" },
  "follow": { phonetic: "/ˈfɒləʊ/", pos: "v.", meaning: "跟随" },
  "stop": { phonetic: "/stɒp/", pos: "v.", meaning: "停止" },
  "create": { phonetic: "/kriˈeɪt/", pos: "v.", meaning: "创造" },
  "speak": { phonetic: "/spiːk/", pos: "v.", meaning: "说" },
  "spoke": { phonetic: "/spəʊk/", pos: "v.", meaning: "说(过去式)" },
  "read": { phonetic: "/riːd/", pos: "v.", meaning: "读" },
  "allow": { phonetic: "/əˈlaʊ/", pos: "v.", meaning: "允许" },
  "add": { phonetic: "/æd/", pos: "v.", meaning: "添加" },
  "spend": { phonetic: "/spend/", pos: "v.", meaning: "花费" },
  "spent": { phonetic: "/spent/", pos: "v.", meaning: "花费(过去式)" },
  "grow": { phonetic: "/ɡrəʊ/", pos: "v.", meaning: "成长" },
  "grew": { phonetic: "/ɡruː/", pos: "v.", meaning: "成长(过去式)" },
  "open": { phonetic: "/ˈəʊpən/", pos: "v.", meaning: "打开" },
  "walk": { phonetic: "/wɔːk/", pos: "v.", meaning: "走" },
  "win": { phonetic: "/wɪn/", pos: "v.", meaning: "赢" },
  "won": { phonetic: "/wʌn/", pos: "v.", meaning: "赢(过去式)" },
  "offer": { phonetic: "/ˈɒfər/", pos: "v.", meaning: "提供" },
  "remember": { phonetic: "/rɪˈmembər/", pos: "v.", meaning: "记得" },
  "love": { phonetic: "/lʌv/", pos: "v.", meaning: "爱" },
  "consider": { phonetic: "/kənˈsɪdər/", pos: "v.", meaning: "考虑" },
  "appear": { phonetic: "/əˈpɪər/", pos: "v.", meaning: "出现" },
  "buy": { phonetic: "/baɪ/", pos: "v.", meaning: "买" },
  "bought": { phonetic: "/bɔːt/", pos: "v.", meaning: "买(过去式)" },
  "wait": { phonetic: "/weɪt/", pos: "v.", meaning: "等待" },
  "serve": { phonetic: "/sɜːv/", pos: "v.", meaning: "服务" },
  "die": { phonetic: "/daɪ/", pos: "v.", meaning: "死" },
  "died": { phonetic: "/daɪd/", pos: "v.", meaning: "死(过去式)" },
  "send": { phonetic: "/send/", pos: "v.", meaning: "发送" },
  "sent": { phonetic: "/sent/", pos: "v.", meaning: "发送(过去式)" },
  "expect": { phonetic: "/ɪkˈspekt/", pos: "v.", meaning: "期望" },
  "build": { phonetic: "/bɪld/", pos: "v.", meaning: "建造" },
  "built": { phonetic: "/bɪlt/", pos: "v.", meaning: "建造(过去式)" },
  "stay": { phonetic: "/steɪ/", pos: "v.", meaning: "停留" },
  "fall": { phonetic: "/fɔːl/", pos: "v.", meaning: "落下" },
  "fell": { phonetic: "/fel/", pos: "v.", meaning: "落下(过去式)" },
  "cut": { phonetic: "/kʌt/", pos: "v.", meaning: "切" },
  "reach": { phonetic: "/riːtʃ/", pos: "v.", meaning: "到达" },
  "kill": { phonetic: "/kɪl/", pos: "v.", meaning: "杀" },
  "remain": { phonetic: "/rɪˈmeɪn/", pos: "v.", meaning: "保持/剩下" },
  "suggest": { phonetic: "/səˈdʒest/", pos: "v.", meaning: "建议" },
  "raise": { phonetic: "/reɪz/", pos: "v.", meaning: "举起/提高" },
  "pass": { phonetic: "/pɑːs/", pos: "v.", meaning: "通过" },
  "sell": { phonetic: "/sel/", pos: "v.", meaning: "卖" },
  "sold": { phonetic: "/səʊld/", pos: "v.", meaning: "卖(过去式)" },
  "require": { phonetic: "/rɪˈkwaɪər/", pos: "v.", meaning: "需要" },
  "report": { phonetic: "/rɪˈpɔːrt/", pos: "v.", meaning: "报告" },
  "decide": { phonetic: "/dɪˈsaɪd/", pos: "v.", meaning: "决定" },
  "pull": { phonetic: "/pʊl/", pos: "v.", meaning: "拉" },
  
  // 数词
  "one": { phonetic: "/wʌn/", pos: "num.", meaning: "一" },
  "two": { phonetic: "/tuː/", pos: "num.", meaning: "二" },
  "three": { phonetic: "/θriː/", pos: "num.", meaning: "三" },
  "four": { phonetic: "/fɔːr/", pos: "num.", meaning: "四" },
  "five": { phonetic: "/faɪv/", pos: "num.", meaning: "五" },
  "six": { phonetic: "/sɪks/", pos: "num.", meaning: "六" },
  "seven": { phonetic: "/ˈsevən/", pos: "num.", meaning: "七" },
  "eight": { phonetic: "/eɪt/", pos: "num.", meaning: "八" },
  "nine": { phonetic: "/naɪn/", pos: "num.", meaning: "九" },
  "ten": { phonetic: "/ten/", pos: "num.", meaning: "十" },
  "hundred": { phonetic: "/ˈhʌndrəd/", pos: "num.", meaning: "百" },
  "thousand": { phonetic: "/ˈθaʊzənd/", pos: "num.", meaning: "千" },
  "million": { phonetic: "/ˈmɪliən/", pos: "num.", meaning: "百万" },
  
  // 其他常用词
  "there": { phonetic: "/ðeər/", pos: "adv.", meaning: "那里" },
  "here": { phonetic: "/hɪər/", pos: "adv.", meaning: "这里" },
  "now": { phonetic: "/naʊ/", pos: "adv.", meaning: "现在" },
  "then": { phonetic: "/ðen/", pos: "adv.", meaning: "那时" },
  "back": { phonetic: "/bæk/", pos: "adv.", meaning: "回来/后面" },
  "away": { phonetic: "/əˈweɪ/", pos: "adv.", meaning: "离开" },
  "out": { phonetic: "/aʊt/", pos: "adv.", meaning: "外面" },
  "up": { phonetic: "/ʌp/", pos: "adv.", meaning: "向上" },
  "down": { phonetic: "/daʊn/", pos: "adv.", meaning: "向下" },
  "off": { phonetic: "/ɒf/", pos: "adv.", meaning: "关闭" },
  "more": { phonetic: "/mɔːr/", pos: "adv.", meaning: "更多" },
  "most": { phonetic: "/məʊst/", pos: "adv.", meaning: "最" },
  "less": { phonetic: "/les/", pos: "adv.", meaning: "更少" },
  "least": { phonetic: "/liːst/", pos: "adv.", meaning: "最少" },
  "very": { phonetic: "/ˈveri/", pos: "adv.", meaning: "非常" },
  "quite": { phonetic: "/kwaɪt/", pos: "adv.", meaning: "相当" },
  "rather": { phonetic: "/ˈrɑːðər/", pos: "adv.", meaning: "相当" },
  "too": { phonetic: "/tuː/", pos: "adv.", meaning: "太" },
  "enough": { phonetic: "/ɪˈnʌf/", pos: "adv.", meaning: "足够" },
  "almost": { phonetic: "/ˈɔːlməʊst/", pos: "adv.", meaning: "几乎" },
  "only": { phonetic: "/ˈəʊnli/", pos: "adv.", meaning: "仅仅" },
  "just": { phonetic: "/dʒʌst/", pos: "adv.", meaning: "只是" },
  "even": { phonetic: "/ˈiːvn/", pos: "adv.", meaning: "甚至" },
  "still": { phonetic: "/stɪl/", pos: "adv.", meaning: "仍然" },
  "yet": { phonetic: "/jet/", pos: "adv.", meaning: "还" },
  "however": { phonetic: "/haʊˈevər/", pos: "adv.", meaning: "然而" },
  "though": { phonetic: "/ðəʊ/", pos: "adv.", meaning: "虽然" },
  "instead": { phonetic: "/ɪnˈsted/", pos: "adv.", meaning: "代替" },
  "especially": { phonetic: "/ɪˈspeʃəli/", pos: "adv.", meaning: "尤其" },
  "particularly": { phonetic: "/pəˈtɪkjələrli/", pos: "adv.", meaning: "特别地" },
  "generally": { phonetic: "/ˈdʒenrəli/", pos: "adv.", meaning: "通常" },
  "usually": { phonetic: "/ˈjuːʒuəli/", pos: "adv.", meaning: "通常" },
  "normally": { phonetic: "/ˈnɔːrməli/", pos: "adv.", meaning: "正常地" },
  "especially": { phonetic: "/ɪˈspeʃli/", pos: "adv.", meaning: "尤其" },
  "especially": { phonetic: "/ɪˈspeʃəli/", pos: "adv.", meaning: "特别地" },
  "mainly": { phonetic: "/ˈmeɪnli/", pos: "adv.", meaning: "主要地" },
  "particularly": { phonetic: "/pəˈtɪkjələrli/", pos: "adv.", meaning: "特别地" },
  "completely": { phonetic: "/kəmˈpliːtli/", pos: "adv.", meaning: "完全地" },
  "totally": { phonetic: "/ˈtəʊtəli/", pos: "adv.", meaning: "完全地" },
  "absolutely": { phonetic: "/ˈæbsəluːtli/", pos: "adv.", meaning: "绝对地" },
  "exactly": { phonetic: "/ɪɡˈzæk tli/", pos: "adv.", meaning: "精确地" },
  "particularly": { phonetic: "/pəˈtɪkjələrli/", pos: "adv.", meaning: "特别地" },
  "especially": { phonetic: "/ɪˈspeʃəli/", pos: "adv.", meaning: "尤其" },
  "simply": { phonetic: "/ˈsɪmpli/", pos: "adv.", meaning: "简单地" },
  "clearly": { phonetic: "/ˈklɪərli/", pos: "adv.", meaning: "清楚地" },
  "obviously": { phonetic: "/ˈɒbviəsli/", pos: "adv.", meaning: "明显地" },
  "certainly": { phonetic: "/ˈsɜːrtnli/", pos: "adv.", meaning: "当然" },
  "probably": { phonetic: "/ˈprɒbəbli/", pos: "adv.", meaning: "可能" },
  "possibly": { phonetic: "/ˈpɒsəbli/", pos: "adv.", meaning: "可能" },
  "perhaps": { phonetic: "/pərˈhæps/", pos: "adv.", meaning: "也许" },
  "maybe": { phonetic: "/ˈmeɪbi/", pos: "adv.", meaning: "也许" },
  "actually": { phonetic: "/ˈæktʃuəli/", pos: "adv.", meaning: "实际上" },
  "really": { phonetic: "/ˈrɪəli/", pos: "adv.", meaning: "真的" },
  "especially": { phonetic: "/ɪˈspeʃli/", pos: "adv.", meaning: "尤其" },
  "especially": { phonetic: "/ɪˈspeʃəli/", pos: "adv.", meaning: "特别" },
  "especially": { phonetic: "/ɪˈspeʃli/", pos: "adv.", meaning: "尤其" },
  
  // 感叹词
  "oh": { phonetic: "/əʊ/", pos: "int.", meaning: "哦" },
  "wow": { phonetic: "/waʊ/", pos: "int.", meaning: "哇" },
  "hey": { phonetic: "/heɪ/", pos: "int.", meaning: "嘿" },
  "please": { phonetic: "/pliːz/", pos: "int.", meaning: "请" },
  "thanks": { phonetic: "/θæŋks/", pos: "int.", meaning: "谢谢" },
  "sorry": { phonetic: "/ˈsɒri/", pos: "int.", meaning: "对不起" },
  "ok": { phonetic: "/əʊˈkeɪ/", pos: "int.", meaning: "好的" },
  "okay": { phonetic: "/əʊˈkeɪ/", pos: "int.", meaning: "好的" },
  "hello": { phonetic: "/həˈləʊ/", pos: "int.", meaning: "你好" },
  "goodbye": { phonetic: "/ɡʊdˈbaɪ/", pos: "int.", meaning: "再见" },
  
  // 常见名词
  "thing": { phonetic: "/θɪŋ/", pos: "n.", meaning: "事情" },
  "something": { phonetic: "/ˈsʌmθɪŋ/", pos: "pron.", meaning: "某事" },
  "anything": { phonetic: "/ˈeniθɪŋ/", pos: "pron.", meaning: "任何事" },
  "everything": { phonetic: "/ˈevriθɪŋ/", pos: "pron.", meaning: "每件事" },
  "nothing": { phonetic: "/ˈnʌθɪŋ/", pos: "pron.", meaning: "没事" },
  "someone": { phonetic: "/ˈsʌmwʌn/", pos: "pron.", meaning: "某人" },
  "anyone": { phonetic: "/ˈeniwʌn/", pos: "pron.", meaning: "任何人" },
  "everyone": { phonetic: "/ˈevriwʌn/", pos: "pron.", meaning: "每个人" },
  "nobody": { phonetic: "/ˈnəʊbədi/", pos: "pron.", meaning: "没人" },
  "anybody": { phonetic: "/ˈenibɒdi/", pos: "pron.", meaning: "任何人" },
  "somewhere": { phonetic: "/ˈsʌmweər/", pos: "adv.", meaning: "某处" },
  "anywhere": { phonetic: "/ˈeniweər/", pos: "adv.", meaning: "任何地方" },
  "everywhere": { phonetic: "/ˈevriweər/", pos: "adv.", meaning: "到处" },
  "nowhere": { phonetic: "/ˈnəʊweər/", pos: "adv.", meaning: "无处" },
  "another": { phonetic: "/əˈnʌðər/", pos: "adj.", meaning: "另一个" },
  "certain": { phonetic: "/ˈsɜːrtn/", pos: "adj.", meaning: "确定的" },
  "available": { phonetic: "/əˈveɪləbl/", pos: "adj.", meaning: "可用的" },
  "similar": { phonetic: "/ˈsɪmələr/", pos: "adj.", meaning: "相似的" },
  "additional": { phonetic: "/əˈdɪʃənl/", pos: "adj.", meaning: "额外的" },
  "current": { phonetic: "/ˈkʌrənt/", pos: "adj.", meaning: "当前的" },
  "previous": { phonetic: "/ˈpriːviəs/", pos: "adj.", meaning: "以前的" },
  "recent": { phonetic: "/ˈriːsnt/", pos: "adj.", meaning: "最近的" },
  "final": { phonetic: "/ˈfaɪnl/", pos: "adj.", meaning: "最终的" },
  "early": { phonetic: "/ˈɜːrli/", pos: "adj.", meaning: "早的" },
  "late": { phonetic: "/leɪt/", pos: "adj.", meaning: "晚的" },
  "latest": { phonetic: "/ˈleɪtɪst/", pos: "adj.", meaning: "最新的" },
  "former": { phonetic: "/ˈfɔːrmər/", pos: "adj.", meaning: "以前的" },
  "second": { phonetic: "/ˈsekənd/", pos: "adj.", meaning: "第二的" },
  "third": { phonetic: "/θɜːrd/", pos: "adj.", meaning: "第三的" },
  "early": { phonetic: "/ˈɜːrli/", pos: "adj.", meaning: "早期的" },
  "late": { phonetic: "/leɪt/", pos: "adj.", meaning: "后期的" },
  "main": { phonetic: "/meɪn/", pos: "adj.", meaning: "主要的" },
  "major": { phonetic: "/ˈmeɪdʒər/", pos: "adj.", meaning: "主要的" },
  "best": { phonetic: "/best/", pos: "adj.", meaning: "最好的" },
  "better": { phonetic: "/ˈbetər/", pos: "adj.", meaning: "更好的" },
  "least": { phonetic: "/liːst/", pos: "adj.", meaning: "最少的" },
  "worse": { phonetic: "/wɜːrs/", pos: "adj.", meaning: "更差的" },
  "worst": { phonetic: "/wɜːrst/", pos: "adj.", meaning: "最差的" },
  "early": { phonetic: "/ˈɜːrli/", pos: "adj.", meaning: "早的" },
  "late": { phonetic: "/leɪt/", pos: "adj.", meaning: "迟的" },
  "near": { phonetic: "/nɪər/", pos: "adj.", meaning: "近的" },
  "far": { phonetic: "/fɑːr/", pos: "adj.", meaning: "远的" },
  "certain": { phonetic: "/ˈsɜːrtn/", pos: "adj.", meaning: "肯定的" },
  "likely": { phonetic: "/ˈlaɪkli/", pos: "adj.", meaning: "可能的" },
  "unlikely": { phonetic: "/ʌnˈlaɪkli/", pos: "adj.", meaning: "不可能的" },
  "able": { phonetic: "/ˈeɪbl/", pos: "adj.", meaning: "能够的" },
  "unable": { phonetic: "/ʌnˈeɪbl/", pos: "adj.", meaning: "不能的" },
  "likely": { phonetic: "/ˈlaɪkli/", pos: "adj.", meaning: "可能的" },
  "unlikely": { phonetic: "/ʌnˈlaɪkli/", pos: "adj.", meaning: "不太可能的" },
  "due": { phonetic: "/duː/", pos: "adj.", meaning: "预期的" },
  "else": { phonetic: "/els/", pos: "adv.", meaning: "其他" },
};

// Tokenize sentence into words
function tokenize(sentence) {
  return sentence
    .toLowerCase()
    .replace(/['']/g, "'")
    .replace(/[,.\-!?;:'"()]/g, ' ')
    .split(/\s+/)
    .filter(word => word.length > 0);
}

// Enrich a single sentence's words
function enrichSentence(sentenceObj) {
  const words = sentenceObj.words || [];
  const existingWords = new Set(words.map(w => w.text?.toLowerCase()).filter(Boolean));
  
  // Get all words from the sentence
  const sentenceWords = tokenize(sentenceObj.sentence);
  
  // Find missing words
  const missingWords = sentenceWords.filter(w => !existingWords.has(w));
  
  // Add missing words with definitions
  const newWords = [...words];
  
  for (const word of missingWords) {
    const def = COMPLETE_DICTIONARY[word];
    if (def) {
      newWords.push({
        text: word,
        phonetic: def.phonetic,
        pos: def.pos,
        meaning: def.meaning
      });
    } else {
      // For unknown words, use a generic format
      newWords.push({
        text: word,
        phonetic: "",
        pos: "",
        meaning: "[未收录]"
      });
    }
  }
  
  return {
    ...sentenceObj,
    words: newWords
  };
}

// Process a course file
function enrichCourseFile(filePath) {
  console.log(`Processing: ${filePath}`);
  
  const content = fs.readFileSync(filePath, 'utf-8');
  const course = JSON.parse(content);
  
  if (!Array.isArray(course)) {
    console.error(`  Error: Not an array: ${filePath}`);
    return;
  }
  
  let totalAdded = 0;
  
  const enriched = course.map(sentence => {
    const originalCount = (sentence.words || []).length;
    const enrichedSentence = enrichSentence(sentence);
    const newCount = enrichedSentence.words.length;
    const added = newCount - originalCount;
    totalAdded += added;
    return enrichedSentence;
  });
  
  // Save enriched course
  fs.writeFileSync(filePath, JSON.stringify(enriched, null, 2), 'utf-8');
  console.log(`  Added ${totalAdded} words`);
}

// Main
function main() {
  const files = fs.readdirSync(DICTS_DIR).filter(f => f.startsWith('course_') && f.endsWith('.json'));
  
  console.log(`Found ${files.length} course files\n`);
  
  for (const file of files) {
    const filePath = path.join(DICTS_DIR, file);
    enrichCourseFile(filePath);
  }
  
  console.log('\nDone!');
}

main();
